version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: creator-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - thecreator-network

  redis:
    image: redis:7-alpine
    container_name: creator-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - thecreator-network

  nest:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: creator-nest
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      REDIS_URL: ${REDIS_URL}
      DB_AUTO_LOAD_ENTITIES: ${DB_AUTO_LOAD_ENTITIES}
      DB_SYNCHRONIZE: ${DB_SYNCHRONIZE}
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      TELEGRAM_STAT_CHAT_ID: ${TELEGRAM_STAT_CHAT_ID}
      SMS_BASE_URL: ${SMS_BASE_URL}
      SMS_API_KEY: ${SMS_API_KEY}
      SMS_EMAIL_COMPANY: ${SMS_EMAIL_COMPANY}
      SDEK_BASE_URL: ${SDEK_BASE_URL}
      SDEK_CLIENT_ID: ${SDEK_CLIENT_ID}
      SDEK_CLIENT_SECRET: ${SDEK_CLIENT_SECRET}
      SDEK_ACCESS_TOKEN: ${SDEK_ACCESS_TOKEN}
      SDEK_ACCESS_TOKEN_CACHE_SECRET: ${SDEK_ACCESS_TOKEN_CACHE_SECRET}
      YOUKASSA_BASE_URL: ${YOUKASSA_BASE_URL}
      YOUKASSA_IDENPOTENT_KEY: ${YOUKASSA_IDENPOTENT_KEY}
      YOUKASSA_SHOP_ID: ${YOUKASSA_SHOP_ID}
      YOUKASSA_SECRET_KEY: ${YOUKASSA_SECRET_KEY}
      RETURNURL_FOR_YOUKASSA: ${RETURNURL_FOR_YOUKASSA}
      YOUKASSA_TRUST_IPS: ${YOUKASSA_TRUST_IPS}
      UNISENDER_API_KEY: ${UNISENDER_API_KEY}
      UNISENDER_API_URL: ${UNISENDER_API_URL}
      THECREATOR_MAIL: ${THECREATOR_MAIL}
      TOCHKA_API_KEY: ${TOCHKA_API_KEY}
      TOCHKA_API_URL: ${TOCHKA_API_URL}
      TOCHKA_WEBHOOK_PUBLIC_KEY_PEM: ${TOCHKA_WEBHOOK_PUBLIC_KEY_PEM}
    networks:
      - thecreator-network

volumes:
  postgres_data:
  redis_data:

networks:
  thecreator-network:
    driver: bridge
    external: true